_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-x86_64
BU.a:
    value: sa
BU.a_dim:
    value: None
BU.a_ffdim:
    value: None
BU.a_layers:
    value: 1
BU.a_nhead:
    value: None
BU.dropout:
    value: None
BU.f:
    value: None
BU.f_dim:
    value: None
BU.f_layers:
    value: 5
BU.f_ln:
    value: None
BU.f_ngp:
    value: None
BU.hid_dim:
    value: None
BU.s_layers:
    value: 1
Bi.a:
    value: sca
Bi.a_dim:
    value: 512
Bi.a_ffdim:
    value: 2048
Bi.a_layers:
    value: 6
Bi.a_nhead:
    value: 8
Bi.dropout:
    value: 0.5
Bi.f:
    value: cnn
Bi.f_dim:
    value: 512
Bi.f_layers:
    value: 10
Bi.f_ln:
    value: true
Bi.f_ngp:
    value: 4
Bi.hid_dim:
    value: 512
Bu.a:
    value: sa
Bu.a_dim:
    value: None
Bu.a_ffdim:
    value: None
Bu.a_layers:
    value: 1
Bu.a_nhead:
    value: None
Bu.dropout:
    value: None
Bu.f:
    value: None
Bu.f_dim:
    value: None
Bu.f_layers:
    value: 5
Bu.f_ln:
    value: None
Bu.f_ngp:
    value: None
Bu.hid_dim:
    value: None
FACT.block:
    value: iuUU
FACT.cmr:
    value: 0.3
FACT.fpos:
    value: true
FACT.mwt:
    value: 0.1
FACT.ntoken:
    value: 30
FACT.trans:
    value: false
Loss.a2fc:
    value: 1
Loss.bgw:
    value: 1
Loss.match:
    value: o2o
Loss.nullw:
    value: -1
Loss.pc:
    value: 1
Loss.sw:
    value: 0
TM.inplace:
    value: true
TM.m:
    value: 5
TM.p:
    value: 0.05
TM.t:
    value: 30
TM.use:
    value: false
aux.cfg_file:
    value: '[]'
aux.debug:
    value: false
aux.eval_every:
    value: 1000
aux.exp:
    value: ""
aux.gpu:
    value: 1
aux.logdir:
    value: log/breakfast/split1/0
aux.mark:
    value: ""
aux.print_every:
    value: 200
aux.resume:
    value: max
aux.runid:
    value: 0
aux.set_cfgs:
    value: None
aux.wandb_offline:
    value: false
aux.wandb_project:
    value: FACT
aux.wandb_user:
    value: ""
batch_size:
    value: 4
clip_grad_norm:
    value: 10
dataset:
    value: breakfast
epoch:
    value: 2
eval_bg:
    value: false
lr:
    value: 0.1
lr_decay:
    value: -1
momentum:
    value: 0.009
optimizer:
    value: SGD
split:
    value: split1
sr:
    value: 1
weight_decay:
    value: 0
